apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-falna
  labels:
    type: local
spec:
  storageClassName: database-falna
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/falna"